language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies from a file
install: "pip install -r requirements.txt --use-mirrors"

# Command to run test for the app
# script: python manage.py test polls
script:
  - coverage run --source=polls manage.py test

after_success:
  - coveralls